# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://delightful-water-000963403.1.azurestaticapps.net

trigger:
  branches:
    include: [ "main", feature/*]

pool:
  vmImage: ubuntu-latest

variables: 
  'deploymentToken': '220b82145480a56bb5b6b5c86e6e6f109c11b91f24c8b99d9e050c02d32b37e81-455ce5f7-a15d-4721-b99b-8b33bbc6846f003108174'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: './'
    api_location: ''
    output_location: ''
  env:
    azure_static_web_apps_api_token: $(deploymentToken)